name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Trigger the deployment on changes to the main branch
    paths:
      - '**/*'  # Deploy all files, adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }} --exclude ".git/*" --exclude "node_modules/*"
          aws s3 website s3://${{ secrets.AWS_BUCKET_NAME }} --index-document index.html --error-document error.html
